"""
LLM / Ollama **informational** metrics and optional QA warnings (never failing checks).

Reads :file:`configs/llm.yaml` for ``ollama.enabled`` and the run’s ``explanations/event_*.md`` files
to report coverage and template-vs.-model heuristics. Ollama does not need to be running.
"""

from __future__ import annotations

import json
import logging
import re
from pathlib import Path
from typing import Any

from fightsafe_ai.exceptions import ConfigurationError


logger = logging.getLogger(__name__)


def _explanation_body_from_file_text(text: str) -> str:
    """Text under ``## Explanation`` in a per-event Markdown file (best-effort)."""
    m = re.search(
        r"^##\s*Explanation\s*\n+(.*?)(?=\n---\s*|\n\*Generated by|\Z)",
        text,
        flags=re.DOTALL | re.MULTILINE,
    )
    return m.group(1).strip() if m else ""


def _is_template_style_body(body: str) -> bool:
    """Heuristic: pipeline template starts with a fixed *Event #… automated pipeline* phrase."""
    s = body.strip()[:500]
    return bool(s) and s.startswith("Event #") and "automated pipeline reported" in s


def _is_llm_style_narrative(body: str) -> bool:
    """
    Heuristic: non-template narrative (Ollama or any non-default wording).

    Empty/parse failure => not treated as model success.
    """
    s = body.strip()
    if not s:
        return False
    return not _is_template_style_body(s)


def load_ollama_enabled_in_default_config() -> bool:
    """``ollama.enabled`` from the project :file:`configs/llm.yaml` (or ``False`` on error)."""
    try:
        from fightsafe_ai.llm.ollama_client import load_ollama_config

        return bool(load_ollama_config(None).enabled)
    except (ConfigurationError, OSError, ValueError, TypeError) as e:
        logger.debug("QA: Ollama config not loaded (%s); treating as disabled", e)
        return False


def _merge_llm_explanation_state_metrics(run_path: Path, metrics: dict[str, Any]) -> None:
    p = run_path / "llm_explanation_state.json"
    if not p.is_file():
        return
    try:
        raw = json.loads(p.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError, TypeError):
        return
    if not isinstance(raw, dict):
        return
    for key in ("llm_requested", "llm_available", "llm_fallback", "llm_error"):
        if key in raw:
            metrics[key] = raw[key]


def build_llm_qa_metrics(
    run_path: Path, n_events: int
) -> tuple[dict[str, Any], list[tuple[str, str]]]:
    """
    Return metrics (``llm_enabled``, ``llm_used``, ``llm_success_rate``) and warning
    messages as ``(check_name, message)`` for :func:`~fightsafe_ai.qa.validators.run_quality_checks`
    to record as **warn**-only :class:`QualityCheckResult` entries.
    """
    run_path = run_path.expanduser().resolve()
    llm_enabled = load_ollama_enabled_in_default_config()

    expl_dir = run_path / "explanations"
    files: list[Path] = []
    if expl_dir.is_dir():
        files = sorted(expl_dir.glob("event_*.md"))
    n_files = len(files)
    llm_used = n_files > 0

    n_model = 0
    for fpath in files:
        try:
            raw = fpath.read_text(encoding="utf-8", errors="replace")
        except OSError as e:
            logger.debug("QA: could not read %s: %s", fpath, e)
            continue
        body = _explanation_body_from_file_text(raw)
        if _is_llm_style_narrative(body):
            n_model += 1

    if n_files == 0:
        llm_success_rate: float | None = None
    else:
        llm_success_rate = float(round(n_model / n_files, 4))

    metrics: dict[str, Any] = {
        "llm_enabled": llm_enabled,
        "llm_used": llm_used,
        "llm_success_rate": llm_success_rate,
    }
    _merge_llm_explanation_state_metrics(run_path, metrics)

    warns: list[tuple[str, str]] = []
    if llm_enabled and n_events > 0 and n_files == 0:
        warns.append(
            (
                "llm_explanations_missing",
                "Ollama is enabled in configs/llm.yaml but this run has no "
                "explanations/event_*.md files; per-event explanations may not have been generated.",
            )
        )
    if n_events > 0 and n_files > 0 and n_files < n_events:
        warns.append(
            (
                "llm_explanations_incomplete",
                f"Found {n_files} per-event explanation file(s) but events.json lists "
                f"{n_events} event(s).",
            )
        )
    if llm_enabled and n_files > 0 and n_model < n_files:
        warns.append(
            (
                "llm_explanations_template_fallback",
                f"{n_files - n_model} of {n_files} per-event explanation(s) use the template "
                "fallback (Ollama may have been unavailable for those).",
            )
        )

    err = metrics.get("llm_error")
    if isinstance(err, str) and err.strip():
        warns.append(
            (
                "llm_explanation_error",
                f"Optional Ollama explanations degraded for this run ({err.strip()}). "
                "Deterministic risk and events were not affected.",
            )
        )

    return metrics, warns


__all__ = [
    "build_llm_qa_metrics",
    "load_ollama_enabled_in_default_config",
]
