"""
Markdown reports for per-event risk explanations (CLI and pipeline).
"""

from __future__ import annotations

import json
import logging
from dataclasses import replace
from pathlib import Path
from typing import Any

import pandas as pd

from fightsafe_ai._metadata import EXPLANATION_SOURCE_LABEL, SAFETY_REPORT_MD_HEADER
from fightsafe_ai.exceptions import ConfigurationError
from fightsafe_ai.llm.base import BaseLLMClient
from fightsafe_ai.llm.config import ExplanationsConfig, load_llm_file_config
from fightsafe_ai.llm.ollama_client import OllamaClient, OllamaClientConfig, load_ollama_config
from fightsafe_ai.llm.risk_explainer import explain_risk_event
from fightsafe_ai.llm.run_state import LLMExplanationRunState
from fightsafe_ai.risk.events import frame_risk_to_events_list
from fightsafe_ai.risk.scorer import compute_interpretable_risk
from fightsafe_ai.risk.time_order import sort_frames_add_timestamp
from fightsafe_ai.utils.sorting import natural_sort_strings


logger = logging.getLogger(__name__)


def _default_llm_yaml() -> Path:
    return Path(__file__).resolve().parents[3] / "configs" / "llm.yaml"


def resolve_ollama_config(llm_config: Path | None) -> OllamaClientConfig:
    """Load ``llm_config`` or fall back to built-in defaults when the file is missing or invalid."""
    p = llm_config if llm_config is not None else _default_llm_yaml()
    if p.is_file():
        try:
            return load_ollama_config(p)
        except (ConfigurationError, OSError, ValueError) as e:
            logger.warning("Ollama config at %s skipped (%s); using defaults", p, e)
    return OllamaClientConfig()


def resolve_explanations_config(llm_config: Path | None) -> ExplanationsConfig:
    p = llm_config if llm_config is not None else _default_llm_yaml()
    if p.is_file():
        try:
            return load_llm_file_config(p).explanations
        except (OSError, ValueError, ConfigurationError) as e:
            logger.debug("Explanations block skipped, using defaults: %s", e)
    return ExplanationsConfig()


def _triggered_cell_to_list(cell: Any) -> list[str]:
    if cell is None or (isinstance(cell, float) and pd.isna(cell)):
        return []
    if isinstance(cell, list):
        return [str(x) for x in cell]
    if isinstance(cell, str):
        s = cell.strip()
        if s.startswith("["):
            try:
                parsed = json.loads(s.replace("'", '"'))
                if isinstance(parsed, list):
                    return [str(x) for x in parsed]
            except json.JSONDecodeError:
                return [s] if s else []
        return [s] if s else []
    return [str(cell)]


def union_triggered_rules_in_segment(
    frame_df: pd.DataFrame,
    start_frame: str | int,
    end_frame: str | int,
    *,
    col_rules: str = "triggered_rules",
) -> list[str]:
    """All distinct rule names that fired in [start_frame, end_frame] (natural order of frames)."""
    if col_rules not in frame_df.columns or len(frame_df) == 0:
        return []
    a = natural_sort_strings(frame_df["frame_id"].astype(str).unique().tolist())
    s, t = str(start_frame), str(end_frame)
    if s not in a or t not in a:
        # best-effort: still filter by string range on sorted list
        a_subset = [x for x in a if s <= x <= t] if a else []
        fids = set(a_subset) or set()
    else:
        i0, i1 = a.index(s), a.index(t)
        fids = set(a[min(i0, i1) : max(i0, i1) + 1])
    sub = frame_df[frame_df["frame_id"].astype(str).isin(fids)]
    seen: list[str] = []
    for v in sub[col_rules].tolist():
        for r in _triggered_cell_to_list(v):
            if r and r not in seen:
                seen.append(r)
    return seen


def build_explanation_markdown(
    event_data: dict[str, Any],
    body: str,
    *,
    source_label: str = EXPLANATION_SOURCE_LABEL,
) -> str:
    """Format a short Markdown page with a fixed footer disclaimer."""
    eid = event_data.get("event_id", "—")
    ev = str(event_data.get("event_level", "—"))
    t0 = event_data.get("start_time")
    t1 = event_data.get("end_time")
    head = f"# Risk event {eid} — **{ev}**"
    meta: list[str] = []
    if t0 is not None and t1 is not None:
        meta.append(f"- **Time range:** {t0:.3f} s – {t1:.3f} s")
    mx = event_data.get("max_risk_score")
    if mx is not None and not (isinstance(mx, float) and mx != mx):
        try:
            meta.append(f"- **Max risk score:** {float(mx):.4f}")
        except (TypeError, ValueError):
            meta.append(f"- **Max risk score:** {mx}")
    if meta:
        head += "\n\n" + "\n".join(meta) + "\n"
    return (
        f"{SAFETY_REPORT_MD_HEADER}\n{head}\n\n---\n\n## Explanation\n\n{body.rstrip()}\n\n"
        f"---\n\n*Generated by {source_label} — not a medical diagnosis. "
        "Computer vision and heuristics provide decision-support only.*\n"
    )


def _noop_llm_client() -> BaseLLMClient:
    class _C(BaseLLMClient):
        def generate(self, prompt: str) -> str:
            raise RuntimeError("LLM disabled; this should not be called when use_llm is False")

    return _C()


def write_explanation_markdown(
    out_path: Path,
    event_data: dict[str, Any],
    *,
    use_ollama: bool,
    ollama_model: str | None = None,
    ollama_temperature: float | None = None,
    ollama_force_enabled: bool = False,
    llm_config: Path | None = None,
    run_state: LLMExplanationRunState | None = None,
) -> str:
    """
    Produce explanation text and write one Markdown file.

    Returns
    -------
    str
        The same explanation string written (after LLM or fallback).
    """
    ocfg = resolve_ollama_config(llm_config)
    if ollama_model is not None and str(ollama_model).strip():
        ocfg = replace(ocfg, model=str(ollama_model).strip())
    if ollama_temperature is not None:
        ocfg = replace(ocfg, temperature=float(ollama_temperature))
    if ollama_force_enabled:
        ocfg = replace(ocfg, enabled=True)
    llm_on = bool(use_ollama and ocfg.enabled)
    client: BaseLLMClient = OllamaClient(ocfg) if llm_on else _noop_llm_client()
    exp = resolve_explanations_config(llm_config)
    text = explain_risk_event(
        event_data,
        client,
        use_llm=llm_on,
        explanations=exp,
        run_state=run_state,
    )
    md = build_explanation_markdown(event_data, text)
    out_path = out_path.resolve()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(md, encoding="utf-8")
    return text


def generate_pipeline_event_explanations(
    features_df: pd.DataFrame,
    fps: float,
    rules_yaml: Path | None,
    out_dir: Path,
    *,
    use_ollama: bool = True,
    ollama_model: str | None = None,
    ollama_temperature: float | None = None,
    ollama_force_enabled: bool = False,
    llm_config: Path | None = None,
) -> int:
    """
    Run interpretable risk, merge event segments, write one ``event_NNNN.md`` per
    **HIGH/CRITICAL** run (per :func:`fightsafe_ai.risk.events.frame_risk_to_events_list`).

    Returns
    -------
    int
        Number of Markdown files created.
    """
    if features_df is None or len(features_df) == 0:
        return 0
    interp = compute_interpretable_risk(features_df, rules_yaml=rules_yaml)
    work = sort_frames_add_timestamp(interp, fps)
    evs = frame_risk_to_events_list(work)
    if not evs:
        return 0
    out_dir = out_dir.resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    ocfg_ex = resolve_ollama_config(llm_config)
    if ollama_model is not None and str(ollama_model).strip():
        ocfg_ex = replace(ocfg_ex, model=str(ollama_model).strip())
    if ollama_temperature is not None:
        ocfg_ex = replace(ocfg_ex, temperature=float(ollama_temperature))
    if ollama_force_enabled:
        ocfg_ex = replace(ocfg_ex, enabled=True)
    llm_on = bool(use_ollama and ocfg_ex.enabled)
    run_state: LLMExplanationRunState | None = (
        LLMExplanationRunState(llm_requested=True) if llm_on else None
    )

    for i, ev in enumerate(evs):
        start_f, end_f = ev["start_frame"], ev["end_frame"]
        rules = union_triggered_rules_in_segment(work, start_f, end_f)
        event_data = {**ev, "triggered_rules": rules}
        eid = int(event_data.get("event_id", i))
        path = out_dir / f"event_{eid:04d}.md"
        write_explanation_markdown(
            path,
            event_data,
            use_ollama=use_ollama,
            ollama_model=ollama_model,
            ollama_temperature=ollama_temperature,
            ollama_force_enabled=ollama_force_enabled,
            llm_config=llm_config,
            run_state=run_state,
        )
    if run_state is not None:
        meta = out_dir.parent / "llm_explanation_state.json"
        meta.write_text(
            json.dumps(run_state.to_public_dict(), indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
    return len(evs)


def infer_run_sampling_fps(run_root: Path) -> float:
    """
    Best-effort FPS for a completed run (for post-hoc explanation regeneration).

    Uses ``risk_scores.csv`` timestamp span; defaults to 10.0 if inference fails.
    """
    from fightsafe_ai.pipeline.output_paths import paths_for_run_root

    p = paths_for_run_root(run_root).risk_scores_csv
    if not p.is_file():
        return 10.0
    try:
        df = pd.read_csv(p)
    except (OSError, ValueError, pd.errors.ParserError):
        return 10.0
    if "timestamp" not in df.columns or len(df) < 2:
        return 10.0
    t = pd.to_numeric(df["timestamp"], errors="coerce").dropna()
    if len(t) < 2:
        return 10.0
    dt = float(t.max() - t.min())
    if dt <= 0:
        return 10.0
    return float((len(t) - 1) / dt) if len(t) > 1 else 10.0


def regenerate_run_event_explanations(
    run_root: Path,
    *,
    use_ollama: bool,
    ollama_model: str | None = None,
    ollama_temperature: float | None = None,
    ollama_force_enabled: bool = False,
    llm_config: Path | None = None,
    rules_yaml: Path | None = None,
    fps: float | None = None,
) -> int:
    """
    Rebuild ``<run_root>/explanations/event_*.md`` from ``features.csv`` (offline reports).

    Returns 0 if ``features.csv`` is missing. Does not raise if Ollama is down; per-event
    :func:`explain_risk_event` falls back to template text and logs a warning.
    """
    from fightsafe_ai.pipeline.output_paths import paths_for_run_root

    run_root = run_root.expanduser().resolve()
    paths = paths_for_run_root(run_root)
    if not paths.features_csv.is_file():
        logger.warning("Cannot regenerate event explanations: missing %s", paths.features_csv)
        return 0
    try:
        feat_df = pd.read_csv(paths.features_csv)
    except (OSError, ValueError, pd.errors.ParserError) as e:
        logger.warning("Failed to read %s: %s", paths.features_csv, e)
        return 0
    f = float(fps) if fps is not None else infer_run_sampling_fps(run_root)
    ryaml = rules_yaml
    if ryaml is None:
        for c in (Path("configs/risk_rules.yaml"), run_root / "risk_rules.yaml"):
            if c.is_file():
                ryaml = c
                break
    out_dir = run_root / "explanations"
    return int(
        generate_pipeline_event_explanations(
            feat_df,
            f,
            ryaml,
            out_dir,
            use_ollama=use_ollama,
            ollama_model=ollama_model,
            ollama_temperature=ollama_temperature,
            ollama_force_enabled=ollama_force_enabled,
            llm_config=llm_config,
        )
    )


__all__ = [
    "LLMExplanationRunState",
    "build_explanation_markdown",
    "generate_pipeline_event_explanations",
    "infer_run_sampling_fps",
    "regenerate_run_event_explanations",
    "resolve_explanations_config",
    "resolve_ollama_config",
    "sort_frames_add_timestamp",
    "union_triggered_rules_in_segment",
    "write_explanation_markdown",
]
