"""
Long-form Markdown reports from a pipeline run directory (re-reads ``risk_scores``,
``events``, per-event ``explanations/`` when present, optional ``qa_report.json``, and
``report.md`` hints). Includes an **AI Explanation (Optional)** section with per-event
LLM or rule-based text and a fixed interpretability disclaimer.
"""

from __future__ import annotations

import html
import logging
import re
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from fightsafe_ai._metadata import (
    DECISION_SUPPORT_SCOPE,
    REPORT_END_ATTRIBUTION,
    SAFETY_REPORT_MD_HEADER,
)
from fightsafe_ai.llm.reporting import resolve_explanations_config
from fightsafe_ai.llm.risk_explainer import fallback_risk_explanation
from fightsafe_ai.reports.summary import (
    build_summary_dict,
    infer_input_video_path,
    load_events_list,
    load_qa_dict,
    load_risk_dataframe,
)


logger = logging.getLogger(__name__)

_AI_EXPLANATION_DISCLAIMER = (
    "LLM-generated explanations are for interpretability only and do not constitute "
    "medical or refereeing decisions."
)


def _parse_explanation_file_body(text: str) -> str:
    """Return text under ``## Explanation`` in a per-event ``explanations/event_*.md`` file."""
    m = re.search(
        r"^##\s*Explanation\s*\n+(.*?)(?=\n---\s*|\n\*Generated by|\Z)",
        text,
        flags=re.DOTALL | re.MULTILINE,
    )
    if not m:
        return ""
    return m.group(1).strip()


def _is_template_style_explanation(body: str) -> bool:
    """Heuristic: pipeline template starts with a fixed 'Event #… automated pipeline' phrase."""
    s = body.strip()[:500]
    return s.startswith("Event #") and "automated pipeline reported" in s


def _classify_explanation_source(body: str) -> str:
    return "rules" if _is_template_style_explanation(body) else "llm"


def _format_triggered_rules(event: dict[str, Any]) -> str:
    r = event.get("triggered_rules", event.get("rules"))
    if r is None:
        return "— (not listed in `events.json`; see `risk_scores` / `features` if present)"
    if isinstance(r, (list, tuple)):
        return ", ".join(str(x) for x in r) if r else "—"
    return str(r)


def _human_review_bullet(event_level: Any) -> str:
    u = str(event_level or "").strip().upper()
    if u in ("HIGH", "CRITICAL"):
        return (
            "Qualified **human review** of the **source video** is **recommended** before any "
            "operational, medical, or sanctioning use of this segment."
        )
    return (
        "A **spot-check** of the segment against the recording remains good practice; low concern "
        "does not prove absence of risk outside the model’s scope."
    )


def _human_review_bullet_plain(event_level: Any) -> str:
    u = str(event_level or "").strip().upper()
    if u in ("HIGH", "CRITICAL"):
        return (
            "Qualified human review of the source video is recommended before any "
            "operational, medical, or sanctioning use of this segment."
        )
    return (
        "A spot-check of the segment against the recording remains good practice; low concern "
        "does not prove absence of risk outside the model’s scope."
    )


@dataclass(frozen=True)
class _EventNarrativePayload:
    event_id: Any
    level: str
    source: str
    time_range: str
    max_risk: str
    rules_context: str
    review_line_md: str
    review_line_plain: str
    narrative: str
    source_note_md: str


def _load_event_narrative_payload(
    run_path: Path, event: dict[str, Any], *, ex_cfg: Any
) -> _EventNarrativePayload:
    eid = event.get("event_id", 0)
    try:
        n = int(eid)
    except (TypeError, ValueError):
        n = 0
    ex_path = run_path / "explanations" / f"event_{n:04d}.md"
    if ex_path.is_file():
        try:
            raw = ex_path.read_text(encoding="utf-8")
        except OSError as e:
            logger.debug("Could not read %s: %s", ex_path, e)
            narrative = fallback_risk_explanation(event, ex_cfg)
            source = "rules"
        else:
            narrative = _parse_explanation_file_body(raw) or fallback_risk_explanation(
                event, ex_cfg
            )
            source = _classify_explanation_source(narrative) if narrative else "rules"
    else:
        narrative = fallback_risk_explanation(event, ex_cfg)
        source = "rules"
    lv = str(event.get("event_level", "—"))
    t0, t1 = event.get("start_time"), event.get("end_time")
    tr = (
        f"{_fmt_num(t0)} s – {_fmt_num(t1)} s"
        if t0 is not None and t1 is not None
        else "— (timestamps not in events.json)"
    )
    smd = (
        "*(**Model** narrative — optional; for interpretability only.)*"
        if source == "llm"
        else "*(**Rule-based** summary from structured event fields.)*"
    )
    return _EventNarrativePayload(
        event_id=eid,
        level=lv,
        source=source,
        time_range=tr,
        max_risk=_fmt_num(event.get("max_risk_score")),
        rules_context=_format_triggered_rules(event),
        review_line_md=_human_review_bullet(lv),
        review_line_plain=_human_review_bullet_plain(lv),
        narrative=narrative.strip(),
        source_note_md=smd,
    )


def _payload_to_markdown(p: _EventNarrativePayload) -> str:
    bq = p.narrative.replace("\n", "\n> ")
    return "\n".join(
        [
            f"#### Event {p.event_id} — **{p.level}** {p.source_note_md}",
            "",
            f"- **Why risk was triggered:** A **{p.level}** segment was merged over **{p.time_range}** "
            "(heuristic run detection from per-frame risk; not a clinical or officiating label).",
            f"- **Signals detected:** Peak **risk score** ≈ {p.max_risk}; **context:** {p.rules_context}.",
            f"- **Human review:** {p.review_line_md}",
            "",
            f"> {bq}",
            "",
        ]
    )


def build_ai_explanations_markdown_block(run_path: Path, events: list[dict[str, Any]]) -> str:
    """
    Markdown fragment for the **AI Explanation (Optional)** section (per-event narratives).

    Uses ``explanations/event_*.md`` when present; otherwise :func:`fallback_risk_explanation`.
    """
    ex_cfg = resolve_explanations_config(None)
    if not events:
        return "*No events in this run — there is nothing to explain at event level.*\n\n"
    parts: list[str] = [f"({_AI_EXPLANATION_DISCLAIMER})\n\n"]
    for ev in events:
        p = _load_event_narrative_payload(run_path, ev, ex_cfg=ex_cfg)
        parts.append(_payload_to_markdown(p))
    return "".join(parts)


def build_ai_explanations_html_fragment(run_path: Path, events: list[dict[str, Any]]) -> str:
    """HTML fragment (escaped) for the AI Explanation block in :func:`generate_html_report`."""

    def esc(s: Any) -> str:
        return html.escape(str(s), quote=False)

    ex_cfg = resolve_explanations_config(None)
    if not events:
        return (
            "<p class='empty'><em>No events in this run — nothing to show at event level.</em></p>"
        )
    out: list[str] = [f'<p class="ai-disclaimer">{esc(_AI_EXPLANATION_DISCLAIMER)}</p>']
    for ev in events:
        p = _load_event_narrative_payload(run_path, ev, ex_cfg=ex_cfg)
        src_lbl = (
            "Model narrative (optional, interpretability only)"
            if p.source == "llm"
            else "Rule-based summary (structured fields)"
        )
        narr = esc(p.narrative)
        if "\n" in p.narrative:
            narr = "<br />\n".join(esc(line) for line in p.narrative.splitlines())
        out.append(
            "<div class='ai-event'>"
            f"<h4>Event {esc(p.event_id)} — <span class='ev-level'>{esc(p.level)}</span> "
            f"<span class='src-tag'>({esc(src_lbl)})</span></h4>"
            "<ul class='ai-bullets'>"
            f"<li><strong>Why risk was triggered:</strong> A <strong>{esc(p.level)}</strong> "
            f"segment was merged over <strong>{esc(p.time_range)}</strong> (heuristic detection from "
            "per-frame risk; not a medical or refereeing label).</li>"
            f"<li><strong>Signals detected:</strong> Peak risk score ≈ <code>{esc(p.max_risk)}</code>; "
            f"context: {esc(p.rules_context)}.</li>"
            f"<li><strong>Human review:</strong> {esc(p.review_line_plain)}</li>"
            "</ul>"
            f'<div class="ai-narrative" role="region" aria-label="Narrative text"><p>{narr}</p></div>'
            "</div>"
        )
    return "\n".join(out)


def _highest_risk_moment(risk_df: pd.DataFrame | None) -> str:
    if risk_df is None or "risk_score" not in risk_df.columns or len(risk_df) == 0:
        return "— (no per-frame risk data available)"
    s = pd.to_numeric(risk_df["risk_score"], errors="coerce")
    if s.isna().all():
        return "— (no numeric risk scores)"
    idx = int(s.idxmax())
    row = risk_df.loc[idx]
    sc = float(s.loc[idx]) if not np.isnan(s.loc[idx]) else float("nan")
    level = row.get("risk_level", "—")
    ts = row.get("timestamp", "—")
    fid = row.get("frame_id", "—")
    return f"**Score:** {sc:.4f} · **Level:** {level} · **t ≈** {ts} s · `frame_id` = `{fid}`"


def _markdown_events_table(events: list[dict[str, Any]]) -> str:
    if not events:
        return "*No events recorded (empty list, or not HIGH/CRITICAL in source pipeline).*\n"
    lines = [
        "| `event_id` | Level | Start (s) | End (s) | max `risk_score` |",
        "| ---: | --- | ---: | ---: | ---: |",
    ]
    for ev in events:
        eid = ev.get("event_id", "—")
        lev = ev.get("event_level", "—")
        t0 = _fmt_num(ev.get("start_time", ev.get("startTime")))
        t1 = _fmt_num(ev.get("end_time", ev.get("endTime")))
        mx = _fmt_num(ev.get("max_risk_score"))
        lines.append(f"| {eid} | {lev} | {t0} | {t1} | {mx} |")
    return "\n".join(lines) + "\n"


def _fmt_num(v: Any) -> str:
    if v is None or (isinstance(v, float) and np.isnan(v)):
        return "—"
    try:
        return f"{float(v):.4f}"
    except (TypeError, ValueError):
        return str(v)


def _qa_block(qa: dict[str, Any] | None) -> str:
    if qa is None:
        return (
            "No `qa_report.json` was found in the run directory. "
            "Run the QA check and export JSON (e.g. "
            "``fightsafe_ai.qa.write_qa_report_json(...)``) to populate this section.\n"
        )
    passed = qa.get("passed", "—")
    w = qa.get("warnings", [])
    n_warn = int(qa.get("warning_count", len(w)))
    lines = [
        f"- **Status:** `{'pass' if passed else 'fail'}` (``passed`` = {passed!r})  \n",
        f"- **Checks (total / failed):** {qa.get('total_checks', '—')} / {qa.get('failed_checks', '—')}  \n",
        f"- **Warnings (count):** {n_warn}  \n",
    ]
    m = qa.get("metrics")
    if isinstance(m, dict) and m:
        sample = {k: m[k] for k in list(m)[:8]}
        lines.append(f"- **Selected QA metrics:** `{sample}`  \n")
    failed_results = [
        r for r in qa.get("results", []) if isinstance(r, dict) and r.get("status") == "fail"
    ]
    if failed_results:
        lines.append("\n**Failed checks (excerpt):**\n\n")
        for r in failed_results[:12]:
            name = r.get("name", "—")
            msg = (r.get("message") or "")[:200]
            lines.append(f"- `{name}`: {msg}\n")
    if w:
        lines.append("\n**Warning messages (excerpt, up to 5):**\n\n")
        for i, x in enumerate(w[:5]):
            lines.append(f"{i + 1}. {x}\n")
    return "".join(lines) + "\n"


def _risk_summary_paragraph(risk_df: pd.DataFrame | None) -> str:
    if risk_df is None or len(risk_df) == 0:
        return "No `risk_scores.csv` rows were available for summarization.\n"
    s = risk_df.get("risk_score")
    if s is None:
        return "—\n"
    sn = pd.to_numeric(s, errors="coerce")
    return (
        f"- **Rows (frames in table):** {len(risk_df)}  \n"
        f"- **min / mean / max risk_score:** {float(sn.min()):.4f} / {float(sn.mean()):.4f} / {float(sn.max()):.4f}  \n"
    )


def _pipeline_outputs_list(run_dir: Path) -> str:
    d = run_dir
    return "\n".join(
        [
            f"- `{d / 'frames'}/` — extracted frames",
            f"- `{d / 'pose_keypoints.csv'}` — MediaPipe keypoints (long format)",
            f"- `{d / 'features.csv'}` — feature table",
            f"- `{d / 'risk_scores.csv'}` — per-frame risk",
            f"- `{d / 'events.json'}` — event segments",
            f"- `{d / 'output_overlay.mp4'}` — overlay video",
            f"- `{d / 'report.md'}` — original pipeline `report.md` (if present)",
        ]
    )


def generate_markdown_report(run_dir: Path, output_path: Path) -> Path:
    """
    Create a **structured** Markdown file with eleven sections, including an optional
    per-event **AI Explanation** block (see module docstring).

    Reads ``risk_scores.csv``, ``events.json``, and ``qa_report.json`` when available.
    """
    run_path = run_dir.expanduser().resolve()
    out = output_path.expanduser().resolve()
    out.parent.mkdir(parents=True, exist_ok=True)

    sum_data = build_summary_dict(run_path)
    risk = load_risk_dataframe(run_path / "risk_scores.csv")
    events = load_events_list(run_path / "events.json")
    qa = load_qa_dict(run_path / "qa_report.json")

    video = (
        infer_input_video_path(run_path / "report.md")
        or "— (set `report.md` or add sidecar to identify)"
    )

    now = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    body = f"""{SAFETY_REPORT_MD_HEADER.rstrip()}

*Generated (UTC): {now}* · *Run path:* `{run_path}`

*Purpose:* {DECISION_SUPPORT_SCOPE}

## 1. Run overview

| Key | Value |
| --- | --- |
| `clip_id` | `{sum_data.get("clip_id", "—")}` |
| `total_frames` (unique / rows) | {sum_data.get("total_frames", 0)} |
| `duration_seconds` (from timestamps) | {sum_data.get("duration_seconds", 0.0):.4f} |
| `max_risk_score` | {sum_data.get("max_risk_score")!s} |
| `number_of_events` | {sum_data.get("number_of_events", 0)} |
| `highest_event_level` | {sum_data.get("highest_event_level")!s} |
| `qa_status` | `{sum_data.get("qa_status", "unknown")}` |

## 2. Input video

Primary path inferred from `report.md` (if any): **{video}**

## 3. Pipeline outputs

{_pipeline_outputs_list(run_path)}

## 4. Risk summary

{_risk_summary_paragraph(risk)}

## 5. Detected events

{_markdown_events_table(events)}

## 6. AI Explanation (Optional)

{build_ai_explanations_markdown_block(run_path, events)}

## 7. Highest risk moment

{_highest_risk_moment(risk)}

## 8. QA summary

{_qa_block(qa)}

## 9. Human review recommendation

Use this file as **decision-support material** (prioritization, review queues, and training
documentation), not as a stand-alone basis for medical decisions or official sanctions. A
qualified **human** should cross-check the overlay video, the source clip, and `events.json`
before any high-stakes action. Automated risk scores and segments are **heuristic**; they are
**not** a substitute for on-site medical assessment, clinical examination, or governing-body
procedures.

## 10. Limitations

Model-based scores depend on **pose tracking quality**, camera angle, **occlusion**, frame
rate, and the configuration in `configs/risk_rules.yaml`. The system may **miss** some
incidents and **false-positive** others. Event boundaries and labels are **operational
conveniences**, not legal, regulatory, or medical facts. **Generalization** to other venues,
sports, or equipment is not guaranteed.

## 11. Safety disclaimer

FightSafe AI is **not** a medical device, **does not** provide a **diagnosis** of injury or
health status, and **must not** be used as the sole source for medical or return-to-activity
decisions. Outputs are intended for **research**, **training**, and **decision support** in
safety workflow design only. Event organizers, officials, and health professionals retain
full responsibility for their decisions. If you are concerned about a possible medical
emergency, follow your venue and emergency medical protocols; do not rely on this report for
emergency care.

{REPORT_END_ATTRIBUTION}
"""
    out.write_text(body, encoding="utf-8")
    logger.info("Wrote Markdown report: %s", out)
    return out


__all__ = [
    "build_ai_explanations_html_fragment",
    "build_ai_explanations_markdown_block",
    "generate_markdown_report",
]
