"""
Project attribution: authors, affiliation, and short strings for CLI and generated text.

Single source of truth to keep README, LICENSE, and exports aligned.
"""

from __future__ import annotations

from typing import Any


# --- Authors (primary) ---------------------------------------------------------

AUTHOR_1_NAME = "David Martin Moncunill"
AUTHOR_1_EMAIL = "david.martinm@ucjc.edu"
AUTHOR_2_NAME = "César Andrés Sánchez"
AUTHOR_2_EMAIL = "cesar.andress@ucjc.edu"

# --- Affiliation (shared) ------------------------------------------------------

AFFILIATION_UNI = "Camilo José Cela University (UCJC)"
AFFILIATION_CITY = "Madrid, Spain"

AFFILIATION_LINE = f"{AFFILIATION_UNI}, {AFFILIATION_CITY}"

# --- Composite strings (use in UI and reports) ---------------------------------

AUTHORS_BIBLIOGRAPHIC = f"{AUTHOR_1_NAME}; {AUTHOR_2_NAME}"

AUTHORS_WITH_EMAILS = f"{AUTHOR_1_NAME} <{AUTHOR_1_EMAIL}>; {AUTHOR_2_NAME} <{AUTHOR_2_EMAIL}>"

# Short form for footers and Typer epilog (single line, wrap-safe)
AUTHORS_SHORT = "D. Martin-Moncunill, C. A. Sánchez"

CLI_EPILOG = f"Authors: {AUTHORS_BIBLIOGRAPHIC} · {AFFILIATION_UNI}, {AFFILIATION_CITY}"

# Default for Markdown "Generated by …" in event explanations
EXPLANATION_SOURCE_LABEL = f"FightSafe AI ({AUTHORS_SHORT}; {AFFILIATION_UNI}, {AFFILIATION_CITY})"

# Clip report: italic subhead under the title
CLIP_REPORT_INTRO = (
    f"Structured algorithmic triage (FightSafe-style pipeline). {AUTHORS_SHORT} · "
    f"{AFFILIATION_UNI}. For research documentation."
)

# Clip report: closing line
REPORT_END_ATTRIBUTION = (
    f"End of report — FightSafe AI · {AUTHORS_BIBLIOGRAPHIC} · {AFFILIATION_LINE}."
)

# Top-of-report block (used in safety Markdown: authors + full affiliation, one line per org level).
REPORT_SAFETY_MD_ATTRIBUTION_BLOCK = (
    f"{AUTHOR_1_NAME} ({AUTHOR_1_EMAIL})\n"
    f"{AUTHOR_2_NAME} ({AUTHOR_2_EMAIL})\n"
    f"\n"
    f"{AFFILIATION_UNI}\n"
    f"{AFFILIATION_CITY}"
)

# One-line statement for machine-readable exports (not medical diagnosis; decision-support scope).
DECISION_SUPPORT_SCOPE = (
    "This output is for research, training, and decision-support use only. "
    "It does not establish medical diagnosis, injury severity, or return-to-activity status."
)

# JSON-friendly attribution (e.g. ``summary.json``) — mirrors REPORT_SAFETY_MD_ATTRIBUTION_BLOCK.
REPORT_ATTRIBUTION_JSON: dict[str, Any] = {
    "authors": [
        {"name": AUTHOR_1_NAME, "email": AUTHOR_1_EMAIL},
        {"name": AUTHOR_2_NAME, "email": AUTHOR_2_EMAIL},
    ],
    "affiliation_lines": [
        AFFILIATION_UNI,
        AFFILIATION_CITY,
    ],
}

# Prefixed to all Markdown safety reports (clip reports + per-event explanations) for traceability.
SAFETY_REPORT_MD_HEADER = f"""# FightSafe AI Safety Report

{REPORT_SAFETY_MD_ATTRIBUTION_BLOCK}

---
"""

__all__ = [
    "AFFILIATION_CITY",
    "AFFILIATION_LINE",
    "AFFILIATION_UNI",
    "AUTHORS_BIBLIOGRAPHIC",
    "AUTHORS_SHORT",
    "AUTHORS_WITH_EMAILS",
    "AUTHOR_1_EMAIL",
    "AUTHOR_1_NAME",
    "AUTHOR_2_EMAIL",
    "AUTHOR_2_NAME",
    "CLIP_REPORT_INTRO",
    "CLI_EPILOG",
    "DECISION_SUPPORT_SCOPE",
    "EXPLANATION_SOURCE_LABEL",
    "REPORT_ATTRIBUTION_JSON",
    "REPORT_END_ATTRIBUTION",
    "REPORT_SAFETY_MD_ATTRIBUTION_BLOCK",
    "SAFETY_REPORT_MD_HEADER",
]
