"""Risk scoring heuristics."""

from fightsafe_ai.risk.adapters import RULE_GROUP, signals_from_feature_row
from fightsafe_ai.risk.engine import RiskEngine, detect_risk_events
from fightsafe_ai.risk.events import (
    COL_DURATION_SECONDS,
    COL_END_FRAME,
    COL_END_TIME,
    COL_EVENT_ID,
    COL_EVENT_LEVEL,
    COL_MAX_RISK_SCORE,
    COL_START_FRAME,
    COL_START_TIME,
    RiskEventExtractionConfig,
    frame_risk_to_events,
    frame_risk_to_events_list,
)
from fightsafe_ai.risk.formal_model import (
    InteractionRule,
    RiskFusionConfig,
    RiskFusionResult,
    RiskSignal,
    SignalGroup,
    apply_interaction_rules,
    compute_fused_risk_score,
    fusion_full_result,
    load_risk_fusion_config,
    map_score_to_levels,
)
from fightsafe_ai.risk.fusion import (
    RiskDecision,
    RiskFusionInput,
    compute_risk_decision,
    fuse_weighted_mean,
)
from fightsafe_ai.risk.levels import RISK_LEVEL_ORDER, max_risk_level, risk_level_rank
from fightsafe_ai.risk.models import RiskRuleParams, risk_rules_from_yaml
from fightsafe_ai.risk.rules import (
    ALL_RULE_NAMES,
    COMBAT_MVP_INDICATOR_LABELS,
    RULE_LIMB_ANOMALY,
    InterpretableRiskConfig,
    build_rule_components,
    load_interpretable_risk_config,
)
from fightsafe_ai.risk.scorer import (
    COL_FIGHTER_ID,
    COL_FRAME_INDEX,
    COL_RISK_LEVEL,
    COL_RISK_SCORE,
    COL_TIMESTAMP,
    COL_TRIGGERED,
    build_combat_mvp_frame_risk,
    compute_interpretable_risk,
)
from fightsafe_ai.risk.surrender import (
    COL_SURRENDER_CONFIDENCE,
    SURRENDER_RULE_KEY,
    SurrenderDetectionResult,
    SurrenderHeuristicConfig,
    apply_surrender_overrides_to_risk_dataframe,
    detect_surrender,
)
from fightsafe_ai.risk.time_order import sort_frames_add_timestamp


__all__ = [
    "ALL_RULE_NAMES",
    "COL_DURATION_SECONDS",
    "COL_END_FRAME",
    "COL_END_TIME",
    "COL_EVENT_ID",
    "COL_EVENT_LEVEL",
    "COL_FIGHTER_ID",
    "COL_FRAME_INDEX",
    "COL_MAX_RISK_SCORE",
    "COL_RISK_LEVEL",
    "COL_RISK_SCORE",
    "COL_START_FRAME",
    "COL_START_TIME",
    "COL_SURRENDER_CONFIDENCE",
    "COL_TIMESTAMP",
    "COL_TRIGGERED",
    "COMBAT_MVP_INDICATOR_LABELS",
    "RISK_LEVEL_ORDER",
    "RULE_GROUP",
    "RULE_LIMB_ANOMALY",
    "SURRENDER_RULE_KEY",
    "InteractionRule",
    "InterpretableRiskConfig",
    "RiskDecision",
    "RiskEngine",
    "RiskEventExtractionConfig",
    "RiskFusionConfig",
    "RiskFusionInput",
    "RiskFusionResult",
    "RiskRuleParams",
    "RiskSignal",
    "SignalGroup",
    "SurrenderDetectionResult",
    "SurrenderHeuristicConfig",
    "apply_interaction_rules",
    "apply_surrender_overrides_to_risk_dataframe",
    "build_combat_mvp_frame_risk",
    "build_rule_components",
    "compute_fused_risk_score",
    "compute_interpretable_risk",
    "compute_risk_decision",
    "detect_risk_events",
    "detect_surrender",
    "frame_risk_to_events",
    "frame_risk_to_events_list",
    "fuse_weighted_mean",
    "fusion_full_result",
    "load_interpretable_risk_config",
    "load_risk_fusion_config",
    "map_score_to_levels",
    "max_risk_level",
    "risk_level_rank",
    "risk_rules_from_yaml",
    "signals_from_feature_row",
    "sort_frames_add_timestamp",
]
