#!/usr/bin/env python3
"""Write paper/tables/quantitative_observations.tex from ablation CSV + risk_series exports."""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path

import pandas as pd


_TOOLS = Path(__file__).resolve().parent
if str(_TOOLS) not in sys.path:
    sys.path.insert(0, str(_TOOLS))
_spec = importlib.util.spec_from_file_location(
    "generate_ablation_paper_assets", _TOOLS / "generate_ablation_paper_assets.py"
)
if _spec is None or _spec.loader is None:
    raise RuntimeError("Cannot load generate_ablation_paper_assets")
_gap = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_gap)
RUN_ORDER = _gap.RUN_ORDER
SELECTED_MODES = _gap.SELECTED_MODES
MODE_SHORT = _gap.MODE_SHORT


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--csv",
        type=Path,
        default=Path("runs/case_studies/ablation_summary/ablation_all_runs.csv"),
        help="Aggregate ablation CSV (same as risk-ablation-all output)",
    )
    p.add_argument(
        "--base-dir",
        type=Path,
        default=Path("runs/case_studies/ablation_summary"),
        help="Directory containing per-run subfolders with risk_series_<mode>.csv",
    )
    p.add_argument(
        "--paper",
        type=Path,
        default=Path("paper"),
        help="Paper root (writes tables/quantitative_observations.tex)",
    )
    args = p.parse_args()

    agg = pd.read_csv(args.csv)
    required = (
        "run_id",
        "ablation_mode",
        "max_risk_score",
        "mean_risk_score",
        "number_of_candidate_events",
    )
    for col in required:
        if col not in agg.columns:
            raise SystemExit(f"Missing column {col} in {args.csv}")

    rows: list[dict[str, float | int | str]] = []
    for run_id in RUN_ORDER:
        rdir = args.base_dir / run_id
        for mode in SELECTED_MODES:
            series_path = rdir / f"risk_series_{mode}.csv"
            if not series_path.is_file():
                raise SystemExit(f"Missing {series_path}; run risk-ablation-all first.")
            sub = agg[(agg["run_id"] == run_id) & (agg["ablation_mode"] == mode)]
            if sub.empty:
                raise SystemExit(f"No row for {run_id=} {mode=} in {args.csv}")
            ts = pd.read_csv(series_path)
            rs = ts["risk_score"].astype(float)
            var_r = float(rs.var(ddof=1)) if len(rs) > 1 else float("nan")
            rows.append(
                {
                    "run_id": run_id,
                    "ablation_mode": mode,
                    "max_risk_score": float(sub.iloc[0]["max_risk_score"]),
                    "mean_risk_score": float(sub.iloc[0]["mean_risk_score"]),
                    "var_risk_score": var_r,
                    "number_of_candidate_events": int(sub.iloc[0]["number_of_candidate_events"]),
                }
            )

    df = pd.DataFrame(rows)

    lines_out: list[str] = []
    for mode in SELECTED_MODES:
        d = df[df["ablation_mode"] == mode]
        lines_out.append(
            f"\\texttt{{{MODE_SHORT[mode]}}} & {_fmt(d['max_risk_score'].mean())} & "
            f"{_fmt(d['mean_risk_score'].mean())} & {_fmt_var(d['var_risk_score'].mean())} & "
            f"{int(d['number_of_candidate_events'].sum())} \\\\"
        )

    tex = (
        "% Auto-generated by tools/generate_quantitative_observations_tex.py — do not edit by hand.\n"
        "\\begin{table}[t]\n"
        "\\centering\n"
        "\\caption{Aggregate behavioral statistics over the six illustrative case-study clips (\\S\\ref{sec:case-studies}). "
        "Means are taken over clips; \\textbf{Var} is the unweighted mean of the per-clip sample variance of "
        "\\texttt{risk\\_score} in \\texttt{risk\\_series\\_<mode>.csv}. "
        "Sums count \\textbf{candidate} events from the aggregate "
        "\\texttt{ablation\\_all\\_runs.csv} file. "
        "\\texttt{FF}=\\texttt{full\\_fusion}, \\texttt{FF\\_NI}=\\texttt{full\\_fusion\\_without\\_interactions}, "
        "\\texttt{FF\\_NL}=\\texttt{full\\_fusion\\_with\\_limb\\_anomaly\\_disabled}. Not semantic accuracy.}\n"
        "\\label{tab:quantitative-ablation-summary}\n"
        "\\small\n"
        "\\begin{tabular}{@{}l r r r r@{}}\n"
        "\\toprule\n"
        "\\textbf{Mode} & \\textbf{Mean $\\max R$} & \\textbf{Mean $\\bar R$} & "
        "\\textbf{Mean Var$(R)$} & \\textbf{$\\sum$ cand.\\ evts.} \\\\\n"
        "\\midrule\n" + "\n".join(lines_out) + "\n\\bottomrule\n"
        "\\end{tabular}\n"
        "\\end{table}\n"
    )

    out = args.paper / "tables" / "quantitative_observations.tex"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(tex, encoding="utf-8")
    print(f"Wrote {out}")


def _fmt(x: float) -> str:
    return f"{float(x):.3f}"


def _fmt_var(x: float) -> str:
    return f"{float(x):.4f}"


if __name__ == "__main__":
    main()
