#!/usr/bin/env python3
"""Generate paper table and figures from ablation_all_runs.csv (curated paper assets)."""

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


SELECTED_MODES = [
    "full_fusion",
    "full_fusion_without_interactions",
    "full_fusion_with_limb_anomaly_disabled",
]

MODE_SHORT = {
    "full_fusion": "FF",
    "full_fusion_without_interactions": "FF\\_NI",
    "full_fusion_with_limb_anomaly_disabled": "FF\\_NL",
}

RUN_ORDER = [
    "case_a_knockdown",
    "case_b_tap",
    "case_c_limb_anomaly",
    "case_d_post_choke_confusion",
    "case_e_manifest_superiority",
    "case_f_referee_errors",
]

CASE_LETTERS = ["A", "B", "C", "D", "E", "F"]


def _fmt_r(x: float) -> str:
    return f"{float(x):.3f}"


def _fmt_pct(x: float) -> str:
    return f"{float(x):.2f}"


def _fmt_ts(x: object) -> str:
    if x is None or (isinstance(x, float) and np.isnan(x)):
        return "---"
    s = str(x).strip()
    if s == "" or s.lower() == "nan":
        return "---"
    try:
        return f"{float(s):.1f}"
    except ValueError:
        return "---"


def write_tex_table(df: pd.DataFrame, path: Path) -> None:
    rows_out: list[str] = []
    for letter, run_id in zip(CASE_LETTERS, RUN_ORDER, strict=True):
        sub = df[(df["run_id"] == run_id) & (df["ablation_mode"].isin(SELECTED_MODES))].set_index(
            "ablation_mode"
        )
        for i, mode in enumerate(SELECTED_MODES):
            if mode not in sub.index:
                raise KeyError(f"Missing {mode} for {run_id}")
            r = sub.loc[mode]
            letter_cell = f"\\textbf{{{letter}}}" if i == 0 else ""
            line = (
                f"{letter_cell} & \\texttt{{{MODE_SHORT[mode]}}} & "
                f"{_fmt_r(r['max_risk_score'])} & {_fmt_r(r['mean_risk_score'])} & "
                f"{float(r['number_of_candidate_events']):.0f} & {_fmt_pct(r['percentage_high_or_critical_frames'])} & "
                f"{_fmt_ts(r['earliest_high_or_critical_timestamp'])} \\\\"
            )
            rows_out.append(line)
        rows_out.append("\\addlinespace")

    body = "\n".join(rows_out).rstrip()
    if body.endswith("\\addlinespace"):
        body = body[: -len("\\addlinespace")].rstrip()

    # Column spec uses @{} padding; must not use f-string brace-escaping for it.
    tex = (
        "% Auto-generated by tools/generate_ablation_paper_assets.py — do not edit by hand.\n"
        "\\begin{table}[t]\n"
        "\\centering\n"
        "\\caption{Behavioral ablation metrics; not semantic accuracy. "
        "Selected modes: \\texttt{FF}=\\texttt{full\\_fusion}, "
        "\\texttt{FF\\_NI}=\\texttt{full\\_fusion\\_without\\_interactions}, "
        "\\texttt{FF\\_NL}=\\texttt{full\\_fusion\\_with\\_limb\\_anomaly\\_disabled}. "
        "\\textbf{H/C \\%} is \\texttt{percentage\\_high\\_or\\_critical\\_frames}. "
        "Cases A--F match \\S\\ref{sec:case-studies} identifiers.}\n"
        "\\label{tab:risk-ablation-selected}\n"
        "\\scriptsize\n"
        "\\setlength{\\tabcolsep}{2.5pt}\n"
        "\\begin{tabular}{@{}l l r r r r r@{}}\n"
        "\\toprule\n"
        "\\textbf{Case} & \\textbf{Mode} & \\textbf{Max $R$} & \\textbf{Mean $R$} & "
        "\\textbf{Cand.\\ evts.} & \\textbf{H/C \\%} & "
        "\\makecell[r]{\\textbf{Earliest}\\\\\\textbf{H/C (s)}} \\\\\n"
        "\\midrule\n"
        f"{body}\n"
        "\\bottomrule\n"
        "\\end{tabular}\n"
        "\\end{table}\n"
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(tex, encoding="utf-8")


def plot_grouped_bars(
    df: pd.DataFrame,
    value_col: str,
    ylabel: str,
    title: str,
    out_path: Path,
) -> None:
    n_cases = len(RUN_ORDER)
    n_modes = len(SELECTED_MODES)
    x = np.arange(n_cases, dtype=float)
    width = 0.25
    offsets = np.linspace(-width, width, n_modes)

    fig, ax = plt.subplots(figsize=(9.5, 4.2), dpi=150)
    colors = ("#2c7fb8", "#fdae61", "#7fbc41")
    legend_labels = ("full fusion", "w/o interactions", "w/o limb anomaly")

    for mi, mode in enumerate(SELECTED_MODES):
        vals = []
        for run_id in RUN_ORDER:
            row = df[(df["run_id"] == run_id) & (df["ablation_mode"] == mode)]
            if len(row) != 1:
                raise ValueError(run_id, mode)
            vals.append(float(row[value_col].iloc[0]))
        ax.bar(
            x + offsets[mi],
            vals,
            width,
            label=legend_labels[mi],
            color=colors[mi],
            edgecolor="black",
            linewidth=0.35,
            alpha=0.92,
        )

    ax.set_xticks(x)
    ax.set_xticklabels(CASE_LETTERS)
    ax.set_xlabel("Case")
    ax.set_ylabel(ylabel)
    ax.set_title(title)
    ax.legend(loc="upper right", fontsize=8, framealpha=0.95)
    ax.grid(axis="y", linestyle="--", alpha=0.35)
    ax.set_axisbelow(True)
    fig.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, bbox_inches="tight")
    plt.close(fig)


REQUIRED_CSV_COLS = (
    "run_id",
    "ablation_mode",
    "max_risk_score",
    "mean_risk_score",
    "number_of_candidate_events",
    "percentage_high_or_critical_frames",
    "earliest_high_or_critical_timestamp",
)


def generate_ablation_paper_assets_from_csv(
    csv_path: Path,
    paper_dir: Path,
) -> None:
    """
    Regenerate ablation table and bar figures under ``paper_dir/tables|figures``.

    Raises ValueError or KeyError if the aggregate CSV is missing required rows/columns.
    """
    df = pd.read_csv(csv_path)
    for col in REQUIRED_CSV_COLS:
        if col not in df.columns:
            raise ValueError(f"Missing column {col!r} in {csv_path}")

    paper_dir = paper_dir.expanduser().resolve()
    write_tex_table(df, paper_dir / "tables" / "ablation_selected_results.tex")
    plot_grouped_bars(
        df,
        "percentage_high_or_critical_frames",
        "High / critical frames (%)",
        "Behavioral ablation metrics; not semantic accuracy.",
        paper_dir / "figures" / "ablation_high_critical_frames.png",
    )
    plot_grouped_bars(
        df,
        "number_of_candidate_events",
        "Candidate event count",
        "Behavioral ablation metrics; not semantic accuracy.",
        paper_dir / "figures" / "ablation_candidate_events.png",
    )


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--csv",
        type=Path,
        default=Path("runs/case_studies/ablation_summary/ablation_all_runs.csv"),
        help="Aggregate ablation CSV",
    )
    p.add_argument(
        "--paper",
        type=Path,
        default=Path("paper"),
        help="Paper directory (writes tables/ and figures/)",
    )
    args = p.parse_args()
    if not args.csv.is_file():
        raise SystemExit(f"CSV not found: {args.csv}")
    try:
        generate_ablation_paper_assets_from_csv(args.csv, args.paper)
    except (KeyError, ValueError) as e:
        raise SystemExit(str(e)) from e
    print(f"Wrote {args.paper / 'tables/ablation_selected_results.tex'}")
    print(f"Wrote {args.paper / 'figures/ablation_high_critical_frames.png'}")
    print(f"Wrote {args.paper / 'figures/ablation_candidate_events.png'}")


if __name__ == "__main__":
    main()
